#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          aws-obd-simulator service
# Required-Start:    can
# Required-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Open OBD simulator service
# Description:       Wrapper for starting / stopping AWS OBD simulator service
#                    Runs when domain 0 boots / shuts down on systems using init.
### END INIT INFO
# Copyright 2022 NXP

SERVER_PATH=/usr/bin/aws-obd-simulator

# Service start function
start_service() {
        cd "${SERVER_PATH}"
        python3 "cansim.py" --interface can1 -o > /var/log/cansim.log 2>&1 &
}

# Service stop function
stop_service() {
        kill -9 $(ps aux | grep '[c]ansim.py' | awk '{print $2}') > /dev/null 2>&1
        sleep 1
}

case "$1" in
start)
        echo "Starting aws-iot-fleetwise simulator service"
        start_service 
        ;;
stop)
        echo "Stopping aws-iot-fleetwise simulator service"
        stop_service 
        ;;
restart)
        echo "Restarting aws-iot-fleetwise simulator service"
        stop_service
        start_service
        ;;

*)
        echo "Usage: /etc/init.d/aws-obd-simulator {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
