# Copyright 2022 NXP
# GoldVIP Update Agents pod - runs on the dom0 VM.
apiVersion: v1
kind: Pod
metadata:
  name: goldvip-update-agents-pod
  labels:
    app: goldvip-update-agents-pod
spec:
  hostNetwork: true
  nodeSelector:
    vmtype: dom0
  # Start the container with a custom command to get the logs from the GoldVIP Update
  # Agents on the rootfs of the host system.
  containers:
  - name: goldvip-update-agents-pod
    image: goldvip-ota-agents:local
    imagePullPolicy: Never
    command: [
      'sh',
      '-c',
      '/home/root/ota/goldvip_uas >> /var/log/ota/goldvip_uas 2>&1'
    ]
    # The Update Agents requires access to some devices on the host (namely /dev/mtd and
    # /dev/mmcblk).
    securityContext:
      privileged: true
    volumeMounts:
    - name: uas-config-path
      mountPath: /etc/ota
    - name: xen-config-path
      mountPath: /etc/xen
    - name: uptane-data-path
      mountPath: /data
    - name: lib-firmware-path
      mountPath: /lib/firmware
    - name: varlog
      mountPath: /var/log/ota
  initContainers:
  - name: init-ota-agents-config-container
    image: goldvip-ota-agents:local
    imagePullPolicy: Never
    command: [
      'sh',
      '-c',
      'if [ ! "$(ls -A /mnt/host-data)" ]; then cp -r /data/* /mnt/host-data; fi; if [ ! "$(ls -A /mnt/uas-config)" ]; then cp -r /etc/ota/* /mnt/uas-config; fi'
    ]
    volumeMounts:
    - name: uas-config-path
      mountPath: /mnt/uas-config
    - name: uptane-data-path
      mountPath: /mnt/host-data
  volumes:
  - name: uas-config-path
    hostPath:
      path: /etc/ota
      type: DirectoryOrCreate
  - name: uptane-data-path
    hostPath:
      path: /data
      type: DirectoryOrCreate
  - name: xen-config-path
    hostPath:
      path: /etc/xen
      type: Directory
  - name: lib-firmware-path
    hostPath:
      path: /lib/firmware
      type: Directory
  - name: varlog
    hostPath:
      path: /var/log/ota
      type: DirectoryOrCreate

