# Copyright 2022 NXP
# Example manifest used to deploy a Nginx web server in a K3s cluster.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # Creates only one pod replica.
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1-alpine
        ports:
        - containerPort: 80
      # Choose the node where the pods will be deployed; by default on Dom0 VM.
      # Remove this option to use all the available nodes for deployment.
      nodeSelector:
        vmtype: dom0
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
