# Copyright 2022 NXP
# DaemonSet used to copy kubeconfig file on worker nodes
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: worker-kubeconfig-provision
  labels:
    k8s-app: worker-kubeconfig-provision
spec:
  selector:
    matchLabels:
      name: worker-kubeconfig-provision
  template:
    metadata:
      labels:
        name: worker-kubeconfig-provision
    spec:
      hostNetwork: true
      nodeSelector:
        vmtype: dom0
      initContainers:
      - name: kubeconfig-provision-pod
        image: worker-kubeconfig-provision:local
        imagePullPolicy: Never
        command: [
          'sh',
          '-c',
          'scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@10.0.100.20:/etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/'
        ]
        volumeMounts:
        - name: k3s-conf
          mountPath: /etc/rancher/k3s
      containers:
      - name: pause
        image: docker.io/rancher/mirrored-pause:3.5
        resources:
      volumes:
      - name: k3s-conf
        hostPath:
          path: /etc/rancher/k3s

