/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Topics.h
  Source: Topics.idl
  Cyclone DDS: V1.4.1

  (c) Copyright 2026 NXP
  All Rights Reserved.

*****************************************************************/
#ifndef DDSC__SHAREDHOST_EXAMPLES_SRC_REFAPPS_GOLDVIP_MPU_SUBSCRIBER_BUILD_LINUX_AARCH64_TOPICS_H_A92BD77E4FBB1FF64AF17A1439A34E74
#define DDSC__SHAREDHOST_EXAMPLES_SRC_REFAPPS_GOLDVIP_MPU_SUBSCRIBER_BUILD_LINUX_AARCH64_TOPICS_H_A92BD77E4FBB1FF64AF17A1439A34E74

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Topics_MotionWise_DDS_HeadLamp
{
  int32_t id;
  uint8_t side;
  uint8_t highBeam;
  uint8_t lowBeam;
  uint8_t dayLight;
  uint8_t fog;
  uint8_t parking;
  bool turn;
} Topics_MotionWise_DDS_HeadLamp;

extern const dds_topic_descriptor_t Topics_MotionWise_DDS_HeadLamp_desc;

#define Topics_MotionWise_DDS_HeadLamp__alloc() \
((Topics_MotionWise_DDS_HeadLamp*) dds_alloc (sizeof (Topics_MotionWise_DDS_HeadLamp)));

#define Topics_MotionWise_DDS_HeadLamp_free(d,o) \
dds_sample_free ((d), &Topics_MotionWise_DDS_HeadLamp_desc, (o))

typedef struct Topics_MotionWise_DDS_RearLight
{
  int32_t id;
  uint8_t side;
  uint8_t tail;
  uint8_t reverse;
  uint8_t brake;
  uint8_t fog;
  uint8_t parking;
  bool turn;
} Topics_MotionWise_DDS_RearLight;

extern const dds_topic_descriptor_t Topics_MotionWise_DDS_RearLight_desc;

#define Topics_MotionWise_DDS_RearLight__alloc() \
((Topics_MotionWise_DDS_RearLight*) dds_alloc (sizeof (Topics_MotionWise_DDS_RearLight)));

#define Topics_MotionWise_DDS_RearLight_free(d,o) \
dds_sample_free ((d), &Topics_MotionWise_DDS_RearLight_desc, (o))

typedef struct Topics_MotionWise_DDS_StopLamp
{
  int32_t id;
  uint8_t intensity;
} Topics_MotionWise_DDS_StopLamp;

extern const dds_topic_descriptor_t Topics_MotionWise_DDS_StopLamp_desc;

#define Topics_MotionWise_DDS_StopLamp__alloc() \
((Topics_MotionWise_DDS_StopLamp*) dds_alloc (sizeof (Topics_MotionWise_DDS_StopLamp)));

#define Topics_MotionWise_DDS_StopLamp_free(d,o) \
dds_sample_free ((d), &Topics_MotionWise_DDS_StopLamp_desc, (o))

typedef struct Topics_MotionWise_DDS_HazardLights
{
  int32_t id;
  bool on;
} Topics_MotionWise_DDS_HazardLights;

extern const dds_topic_descriptor_t Topics_MotionWise_DDS_HazardLights_desc;

#define Topics_MotionWise_DDS_HazardLights__alloc() \
((Topics_MotionWise_DDS_HazardLights*) dds_alloc (sizeof (Topics_MotionWise_DDS_HazardLights)));

#define Topics_MotionWise_DDS_HazardLights_free(d,o) \
dds_sample_free ((d), &Topics_MotionWise_DDS_HazardLights_desc, (o))

typedef struct Topics_MotionWise_DDS_LicensePlateLight
{
  int32_t id;
  bool on;
} Topics_MotionWise_DDS_LicensePlateLight;

extern const dds_topic_descriptor_t Topics_MotionWise_DDS_LicensePlateLight_desc;

#define Topics_MotionWise_DDS_LicensePlateLight__alloc() \
((Topics_MotionWise_DDS_LicensePlateLight*) dds_alloc (sizeof (Topics_MotionWise_DDS_LicensePlateLight)));

#define Topics_MotionWise_DDS_LicensePlateLight_free(d,o) \
dds_sample_free ((d), &Topics_MotionWise_DDS_LicensePlateLight_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__SHAREDHOST_EXAMPLES_SRC_REFAPPS_GOLDVIP_MPU_SUBSCRIBER_BUILD_LINUX_AARCH64_TOPICS_H_A92BD77E4FBB1FF64AF17A1439A34E74 */
